import { Component } from '@angular/core';

@Component({
  selector: 'app-filto-tabla',
  templateUrl: './filto-tabla.component.html',
  styleUrl: './filto-tabla.component.scss'
})
export class FiltoTablaComponent {
  
  dropdowns = [
    {
      title: 'System',
      items: [
        'BRAKES', 'SUSPENSION', 'ENGINE & DRIVETRAIN', 'CHASSIS & BODY', 
        'MISC., FIT & FINISH & ASSEMBLY', 'ELECTRICAL', 
        'WHEELS, WHEEL BEARINGS & TIRES', 'STEERING'
      ],
      isOpen: false
    },
    {
      title: 'Assembly',
      items: [
        'BALANCE CAR', 'BRAKE DISCS', 'BRAKE FLUID', 'BRAKE LINES', 'BRAKE MASTER CYLINDER',
        'BRAKE PADS', 'BRAKE SYSTEM FRONT', 'BRAKE SYSTEM REAR', 'CALIPERS', 'FASTENERS',
        'PROPORTIONING VALVE', 'A-ARMS FRONT LOWER', 'A-ARMS FRONT UPPER', 'A-ARMS REAR LOWER',
        'A-ARMS REAR UPPER', 'ANTI ROLL BAR FRONT', 'ANTI ROLL BAR REAR', 'BELL CRANKS',
        'BELL CRANKS FRONT', 'BELL CRANKS REAR', 'BRACKERS', 'DAMPER SYSTEM FRONT', 
        'DAMPER SYSTEM REAR', 'FRONT A/ARMS OR EQUIVALENT', 'FRONT UPRIGHTS', 'PUSH/PULLROD FRONT', 
        'PUSH/PULLROD REAR', 'REAR A/ARMS OR EQUIVALENT', 'REAR UPRIGHTS', 'ROD ENDS', 'SHOCKS FRONT', 
        'SHOCKS REAR', 'SPRINGS', 'SUSPENSION MECHANISM', 'TIE ROD - FRONT', 'TIE ROD - REAR', 
        'AIR FILTER', 'AIRBOX', 'AXLES', 'CV JOINTS/U JOINTS', 'CARBURETOR', 'CHAIN / BELT', 
        'CLUTCH', 'COOLANT', 'COOLANT LINES', 'COOLING SYSTEM', 'DIFFERENTIAL', 'DIFFERENTIAL BEARINGS',
        'DIFFERENTIAL MOUNTS', 'DRIVESHAFT ASSEMBLY', 'DRIVETRAIN ASSEMBLY', 'ENGINE', 'ENGINE MOUNTS',
        'ENGINE/DIFF OIL', 'EXHAUST MANIFOLD', 'EXHAUST SYSTEM', 'FUEL FILTER', 'FUEL INJECTORS', 
        'FUEL LINES/RAILS', 'FUEL PRESSURE REG.', 'FUEL PUMP', 'FUEL TANK - NOT THE HV-BATTERY', 
        'FUEL VENT/CHECK VALVE', 'GEARBOX', 'HOSE CLAMS', 'INTAKE MANIFOLD', 'INTAKE SYSTEM', 'MUFFLER', 
        'OIL COOLER', 'OVERFLOW BOTTLES', 'RADIATOR', 'RADIATOR FANS', 'RESTRICTOR', 'SHIELDS', 
        'SPROCKET/PULLEYS', 'THROTTLE BODY', 'TRANSMISSION', 'TURBO/SUPER CHARGER', 'AERODYNAMIC WING (IF USED)', 
        'AERODYNAMICS DRS', 'AERODYNAMICS FRONT WING', 'AERODYNAMICS REAR WING', 'AERODYNAMICS SIDE WING', 
        'AERODYNAMICS UNDERBODY', 'AUTONOMOUS EBS', 'BODY ATTACHMENTS', 'BODY MATERIAL', 'BODY PROCESSING', 
        'BRACKETS', 'CHASSIS ASSEMBLY', 'CRASH BOX', 'FLOOR PAN', 'FRAME/FRAME TUBES', 'FRONT HOOP', 
        'FRONT PART FRAME', 'IMPACT ATTENUATOR', 'MAIN HOOP', 'MONOCOQUE', 'MOUNTS INTEGRAL TO FRAME', 
        'PEDAL (ACCELERATOR)', 'PEDAL (BRAKE)', 'PEDALS', 'REAR FRAME', 'SHIFTER', 'SHIFTER CABLE/LINKAGE', 
        'THROTTLE CONTROLS', 'TUBE END PREPS', 'TUBE CUTS/BENDS', 'STEERING RACK', 'STEERING SHAFT', 
        'STEERING WHEEL', 'STEERING WHEEL QUICK RELEASE', 'TIE RODS', 'FRONT HUBS', 'LUG NUTS', 'REAR HUBS', 
        'TIRES', 'VALVE STEMS', 'WHEEL BEARINGS', 'WHEEL STUDS', 'WHEEL WHEIGHTS', 'WHEELS', 'ACCUMULATOR', 
        'ACCUMULATOR CONTAINER', 'ACCUMULATOR COOLING', 'AUTONOMOUS ACCELERATION SYSTEM', 'AUTONOMOUS BOX', 
        'AUTONOMOUS BRAKE SYSTEM', 'AUTONOMOUS CAMERA SYSTEM', 'AUTONOMOUS LIDAR SYSTEM', 
        'AUTONOMOUS RADAR SYSTEM', 'AUTONOMOUS STEERING SYSTEM', 'AUTONOMOUS SYSTEM', 'BSPD', 'BRAKE LIGHT', 
        'BULBS', 'CONTROL UNIT', 'DASH PANEL', 'ECM/ENGINE ELECTRONICS', 'FUSES', 'HV-BATTERY', 
        'INDICATOR LIGHTS', 'KILL SWITCH', 'LV-BATTERY', 'OILS PRESSURE GAGE/LIGHT', 'RELAYS', 'SENSORS', 
        'SOLENOIDS', 'STARTER BUTTON', 'TSAL/ASSI', 'TACHOMETER', 'TELEMETRY', 'VCU', 'WATER TERMPERATURE GAGE', 
        'WIRE HARNESS/CONNECTORS', 'DRIVER\'S HARNESS', 'FIRE WALL', 'HEADREST/RESTRAINTS', 'MIRRORS', 
        'PAINT - BODY', 'PAINT - FRAME', 'SEATS', 'OTHERS'
      ],
      isOpen: false
    },
    {
      title: 'System Code',
      items: ['BR', 'SU', 'EN', 'FR', 'MS', 'EL', 'WT'],
      isOpen: false
    },
    {
      title: 'FUEM DPT',
      items: ['VD', 'EN', 'AE', 'CH', 'EN'],
      isOpen: false
    }
  ];
}